version: 0.2

phases:

  build:
    commands:
      - echo "Build started on `date`"
      - echo "Running mvn package"
      - cd lab1-aws-basics
      - bash -c  "mvn package"
      - echo "Running cdk to build env and provision application"
      - cd ops-environment
      - bash -c  "cdk deploy"

  post_build:
    commands:
      - echo "Build completed on `date`"

cache:
  paths:
    - '/root/.m2/**/*'
